/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.privatemovie.tv.dto.models

import com.privatemovie.tv.dto.models.VideoSource

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param title 
 * @param order 
 * @param createdAt 
 * @param updatedAt 
 * @param videoSources 
 * @param description 
 * @param seasonId 
 * @param thumbnailUrl 
 * @param rating 
 */
@Serializable

data class EpisodeWithSources (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "order")
    val order: kotlin.Int,

    @SerialName(value = "createdAt")
    val createdAt: kotlin.String,

    @SerialName(value = "updatedAt")
    val updatedAt: kotlin.String,

    @SerialName(value = "videoSources")
    val videoSources: kotlin.collections.List<VideoSource>,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "seasonId")
    val seasonId: kotlin.String? = null,

    @SerialName(value = "thumbnailUrl")
    val thumbnailUrl: kotlin.String? = null,

    @SerialName(value = "rating")
    val rating: kotlin.String? = null

) {


}

