/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.privatemovie.tv.dto.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param code Machine-readable code derived from the backend error class name (e.g. SERIES_NOT_FOUND).
 * @param message 
 */
@Serializable

data class ErrorObject (

    /* Machine-readable code derived from the backend error class name (e.g. SERIES_NOT_FOUND). */
    @SerialName(value = "code")
    val code: kotlin.String,

    @SerialName(value = "message")
    val message: kotlin.String

) {


}

