/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.privatemovie.tv.dto.models

import com.privatemovie.tv.dto.models.EpisodeWithSources

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param seriesId 
 * @param title 
 * @param status 
 * @param createdAt 
 * @param updatedAt 
 * @param episodes 
 * @param description 
 * @param posterUrl 
 * @param seasonNumber 
 */
@Serializable

data class SeasonWithEpisodes (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "seriesId")
    val seriesId: kotlin.String,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "status")
    val status: kotlin.String,

    @SerialName(value = "createdAt")
    val createdAt: kotlin.String,

    @SerialName(value = "updatedAt")
    val updatedAt: kotlin.String,

    @SerialName(value = "episodes")
    val episodes: kotlin.collections.List<EpisodeWithSources>,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "posterUrl")
    val posterUrl: kotlin.String? = null,

    @SerialName(value = "seasonNumber")
    val seasonNumber: kotlin.Int? = null

) {


}

