/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.privatemovie.tv.dto.models

import com.privatemovie.tv.dto.models.Genre

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param title 
 * @param type 
 * @param isFeatured 
 * @param createdAt 
 * @param updatedAt 
 * @param genres 
 * @param seasonsCount 
 * @param episodesCount 
 * @param description 
 * @param posterUrl 
 * @param backdropUrl 
 * @param rating 
 */
@Serializable

data class SeriesMetadata (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "type")
    val type: kotlin.String,

    @SerialName(value = "isFeatured")
    val isFeatured: kotlin.Boolean,

    @SerialName(value = "createdAt")
    val createdAt: kotlin.String,

    @SerialName(value = "updatedAt")
    val updatedAt: kotlin.String,

    @SerialName(value = "genres")
    val genres: kotlin.collections.List<Genre>,

    @SerialName(value = "seasonsCount")
    val seasonsCount: kotlin.Int,

    @SerialName(value = "episodesCount")
    val episodesCount: kotlin.Int,

    @SerialName(value = "description")
    val description: kotlin.String? = null,

    @SerialName(value = "posterUrl")
    val posterUrl: kotlin.String? = null,

    @SerialName(value = "backdropUrl")
    val backdropUrl: kotlin.String? = null,

    @SerialName(value = "rating")
    val rating: kotlin.String? = null

) {


}

