/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.privatemovie.tv.dto.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param episodeId 
 * @param type Client-consumable playback target kind ('embed' for WebView playback, 'direct' for native player).
 * @param url Normalized client-consumable playback target URL (e.g. /embed/{hash} for videobello embeds or direct video stream URL).
 * @param label 
 * @param createdAt 
 * @param updatedAt 
 * @param quality 
 */
@Serializable

data class VideoSource (

    @SerialName(value = "id")
    val id: kotlin.String,

    @SerialName(value = "episodeId")
    val episodeId: kotlin.String,

    /* Client-consumable playback target kind ('embed' for WebView playback, 'direct' for native player). */
    @SerialName(value = "type")
    val type: VideoSource.Type,

    /* Normalized client-consumable playback target URL (e.g. /embed/{hash} for videobello embeds or direct video stream URL). */
    @SerialName(value = "url")
    val url: kotlin.String,

    @SerialName(value = "label")
    val label: kotlin.String,

    @SerialName(value = "createdAt")
    val createdAt: kotlin.String,

    @SerialName(value = "updatedAt")
    val updatedAt: kotlin.String,

    @SerialName(value = "quality")
    val quality: kotlin.String? = null

) {

    /**
     * Client-consumable playback target kind ('embed' for WebView playback, 'direct' for native player).
     *
     * Values: EMBED,DIRECT
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "embed") EMBED("embed"),
        @SerialName(value = "direct") DIRECT("direct"),
        @SerialName(value = "s3") S3("s3");
    }

}

