export interface Series {
  id: string;
  title: string;
  description: string;
  thumbnail: string;
  episodeCount: number;
  source: string;
  genres: string[];
}

export interface DummyVideo {
  id: string;
  seriesId: string;
  title: string;
  source: string;
  videoType: string | null;
  videoUrl: string;
  thumbnail: string;
  createdAt: Date;
  sourceUrl: string;
  metadata: Record<string, unknown> | null;
}

export const dummySeries: Series[] = [
  {
    id: 'mushoku-tensei',
    title: 'Mushoku Tensei',
    description: 'A 34-year-old NEET dies and is reincarnated into a world of magic, vowing to live his new life without regrets.',
    thumbnail: 'https://picsum.photos/seed/mushoku-series/320/180',
    episodeCount: 2,
    source: 'otakudesu',
    genres: ['Fantasy', 'Adventure'],
  },
  {
    id: 'one-punch-man',
    title: 'One Punch Man',
    description: 'The strongest hero, Saitama, can defeat any enemy with a single punch — and he\'s bored by it.',
    thumbnail: 'https://picsum.photos/seed/opm-series/320/180',
    episodeCount: 2,
    source: 'otakudesu',
    genres: ['Action', 'Comedy'],
  },
  {
    id: 'frieren',
    title: 'Sousou no Frieren',
    description: 'An elf mage journeys through a world that has moved on after her adventuring party defeated the Demon King.',
    thumbnail: 'https://picsum.photos/seed/frieren-series/320/180',
    episodeCount: 1,
    source: 'otakudesu',
    genres: ['Adventure', 'Fantasy'],
  },
  {
    id: 'dungeon-meshi',
    title: 'Dungeon Meshi',
    description: 'A party of adventurers must cook and eat monsters to survive a deep dungeon.',
    thumbnail: 'https://picsum.photos/seed/dungeon-meshi-series/320/180',
    episodeCount: 1,
    source: 'otakudesu',
    genres: ['Comedy', 'Fantasy'],
  },
  {
    id: 'jujutsu-kaisen',
    title: 'Jujutsu Kaisen',
    description: 'A boy swallows a cursed talisman and becomes entangled in the world of sorcerers and curses.',
    thumbnail: 'https://picsum.photos/seed/jjk-series/320/180',
    episodeCount: 1,
    source: 'otakudesu',
    genres: ['Action', 'Supernatural'],
  },
  {
    id: 'vinland-saga',
    title: 'Vinland Saga',
    description: 'A young Viking seeks revenge against the man who killed his father in this epic historical saga.',
    thumbnail: 'https://picsum.photos/seed/vinland-series/320/180',
    episodeCount: 1,
    source: 'otakudesu',
    genres: ['Action', 'Historical'],
  },
  {
    id: 'aot',
    title: 'Attack on Titan',
    description: 'Humanity fights for survival against man-eating giants in a world of walls and desperation.',
    thumbnail: 'https://picsum.photos/seed/aot-series/320/180',
    episodeCount: 1,
    source: 'otakudesu',
    genres: ['Action', 'Drama'],
  },
  {
    id: 'oshi-no-ko',
    title: 'Oshi no Ko',
    description: 'A reincarnation drama set in the dark underbelly of the entertainment industry.',
    thumbnail: 'https://picsum.photos/seed/oshi-series/320/180',
    episodeCount: 1,
    source: 'otakudesu',
    genres: ['Drama', 'Supernatural'],
  },
  {
    id: 'one-piece',
    title: 'One Piece',
    description: 'Monkey D. Luffy and his pirate crew search for the ultimate treasure, the One Piece.',
    thumbnail: 'https://picsum.photos/seed/onepiece-series/320/180',
    episodeCount: 1,
    source: 'otakudesu',
    genres: ['Adventure', 'Shounen'],
  },
  {
    id: 'demon-slayer',
    title: 'Demon Slayer',
    description: 'A boy becomes a demon slayer to avenge his family and cure his sister.',
    thumbnail: 'https://picsum.photos/seed/demonslayer-series/320/180',
    episodeCount: 1,
    source: 'otakudesu',
    genres: ['Action', 'Supernatural'],
  },
  {
    id: 'spy-x-family',
    title: 'Spy x Family',
    description: 'A spy, an assassin, and a telepath form a fake family for a top-secret mission.',
    thumbnail: 'https://picsum.photos/seed/spyfamily-series/320/180',
    episodeCount: 1,
    source: 'otakudesu',
    genres: ['Comedy', 'Action'],
  },
];

export const dummyVideos: DummyVideo[] = [
  {
    id: '1',
    seriesId: 'frieren',
    title: 'Sousou no Frieren — Episode 28',
    source: 'otakudesu',
    videoType: 'TV',
    videoUrl: 'https://example.com/embed/frieren-28',
    thumbnail: 'https://picsum.photos/seed/frieren/320/180',
    createdAt: new Date('2025-08-10T14:30:00Z'),
    sourceUrl: 'https://otakudesu.cloud/episode/frieren-28',
    metadata: { duration: '24 min', genres: ['Adventure', 'Fantasy'] },
  },
  {
    id: '2',
    seriesId: 'dungeon-meshi',
    title: 'Dungeon Meshi — Episode 24',
    source: 'otakudesu',
    videoType: 'TV',
    videoUrl: 'https://example.com/embed/dungeon-meshi-24',
    thumbnail: 'https://picsum.photos/seed/dungeon-meshi/320/180',
    createdAt: new Date('2025-08-08T12:00:00Z'),
    sourceUrl: 'https://otakudesu.cloud/episode/dungeon-meshi-24',
    metadata: { duration: '24 min', genres: ['Comedy', 'Fantasy'] },
  },
  {
    id: '3',
    seriesId: 'jujutsu-kaisen',
    title: 'Jujutsu Kaisen — Season 2 Episode 23',
    source: 'otakudesu',
    videoType: 'TV',
    videoUrl: 'https://example.com/embed/jjk-s2-23',
    thumbnail: 'https://picsum.photos/seed/jjk/320/180',
    createdAt: new Date('2025-08-05T18:00:00Z'),
    sourceUrl: 'https://otakudesu.cloud/episode/jjk-s2-23',
    metadata: { duration: '23 min', genres: ['Action', 'Supernatural'] },
  },
  {
    id: '4',
    seriesId: 'vinland-saga',
    title: 'Vinland Saga — Season 2 Episode 24',
    source: 'otakudesu',
    videoType: 'TV',
    videoUrl: 'https://example.com/embed/vinland-s2-24',
    thumbnail: 'https://picsum.photos/seed/vinland/320/180',
    createdAt: new Date('2025-08-03T10:00:00Z'),
    sourceUrl: 'https://otakudesu.cloud/episode/vinland-s2-24',
    metadata: { duration: '25 min', genres: ['Action', 'Historical'] },
  },
  {
    id: '5',
    seriesId: 'aot',
    title: 'Attack on Titan — The Final Chapters',
    source: 'otakudesu',
    videoType: 'Movie',
    videoUrl: 'https://example.com/embed/aot-final',
    thumbnail: 'https://picsum.photos/seed/aot/320/180',
    createdAt: new Date('2025-07-28T20:00:00Z'),
    sourceUrl: 'https://otakudesu.cloud/episode/aot-final',
    metadata: { duration: '2h 1m', genres: ['Action', 'Drama'] },
  },
  {
    id: '6',
    seriesId: 'oshi-no-ko',
    title: 'Oshi no Ko — Episode 11',
    source: 'otakudesu',
    videoType: 'TV',
    videoUrl: 'https://example.com/embed/oshi-11',
    thumbnail: 'https://picsum.photos/seed/oshi/320/180',
    createdAt: new Date('2025-07-25T16:00:00Z'),
    sourceUrl: 'https://otakudesu.cloud/episode/oshi-11',
    metadata: { duration: '24 min', genres: ['Drama', 'Supernatural'] },
  },
  {
    id: '7',
    seriesId: 'one-piece',
    title: 'One Piece — Episode 1092',
    source: 'otakudesu',
    videoType: 'TV',
    videoUrl: 'https://example.com/embed/one-piece-1092',
    thumbnail: 'https://picsum.photos/seed/onepiece/320/180',
    createdAt: new Date('2025-07-22T09:30:00Z'),
    sourceUrl: 'https://otakudesu.cloud/episode/one-piece-1092',
    metadata: { duration: '24 min', genres: ['Adventure', 'Shounen'] },
  },
  {
    id: '8',
    seriesId: 'demon-slayer',
    title: 'Demon Slayer — Hashira Training Arc',
    source: 'otakudesu',
    videoType: 'TV',
    videoUrl: 'https://example.com/embed/ds-hashira',
    thumbnail: 'https://picsum.photos/seed/demonslayer/320/180',
    createdAt: new Date('2025-07-18T14:00:00Z'),
    sourceUrl: 'https://otakudesu.cloud/episode/ds-hashira',
    metadata: { duration: '26 min', genres: ['Action', 'Supernatural'] },
  },
  {
    id: '9',
    seriesId: 'spy-x-family',
    title: 'Spy x Family — Season 3 Episode 1',
    source: 'otakudesu',
    videoType: 'TV',
    videoUrl: 'https://example.com/embed/spy-x-family-s3-1',
    thumbnail: 'https://picsum.photos/seed/spyfamily/320/180',
    createdAt: new Date('2025-07-15T11:00:00Z'),
    sourceUrl: 'https://otakudesu.cloud/episode/spy-x-family-s3-1',
    metadata: { duration: '24 min', genres: ['Comedy', 'Action'] },
  },
  {
    id: '10',
    seriesId: 'mushoku-tensei',
    title: 'Mushoku Tensei — Season 2 Episode 12',
    source: 'otakudesu',
    videoType: 'TV',
    videoUrl: 'https://example.com/embed/mushoku-s2-12',
    thumbnail: 'https://picsum.photos/seed/mushoku/320/180',
    createdAt: new Date('2025-07-12T15:00:00Z'),
    sourceUrl: 'https://otakudesu.cloud/episode/mushoku-s2-12',
    metadata: { duration: '24 min', genres: ['Fantasy', 'Adventure'] },
  },
  {
    id: '11',
    seriesId: 'mushoku-tensei',
    title: 'Mushoku Tensei — Season 2 Episode 13',
    source: 'otakudesu',
    videoType: 'TV',
    videoUrl: 'https://example.com/embed/mushoku-s2-13',
    thumbnail: 'https://picsum.photos/seed/mushoku2/320/180',
    createdAt: new Date('2025-07-19T15:00:00Z'),
    sourceUrl: 'https://otakudesu.cloud/episode/mushoku-s2-13',
    metadata: { duration: '24 min', genres: ['Fantasy', 'Adventure'] },
  },
  {
    id: '12',
    seriesId: 'one-punch-man',
    title: 'One Punch Man — Season 2 Episode 12',
    source: 'otakudesu',
    videoType: 'TV',
    videoUrl: 'https://example.com/embed/opm-s2-12',
    thumbnail: 'https://picsum.photos/seed/opm1/320/180',
    createdAt: new Date('2025-06-10T15:00:00Z'),
    sourceUrl: 'https://otakudesu.cloud/episode/opm-s2-12',
    metadata: { duration: '24 min', genres: ['Action', 'Comedy'] },
  },
  {
    id: '13',
    seriesId: 'one-punch-man',
    title: 'One Punch Man — Season 2 Episode 13',
    source: 'otakudesu',
    videoType: 'TV',
    videoUrl: 'https://example.com/embed/opm-s2-13',
    thumbnail: 'https://picsum.photos/seed/opm2/320/180',
    createdAt: new Date('2025-06-17T15:00:00Z'),
    sourceUrl: 'https://otakudesu.cloud/episode/opm-s2-13',
    metadata: { duration: '24 min', genres: ['Action', 'Comedy'] },
  },
];