/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FormRouteImport } from './routes/form'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminGenresRouteImport } from './routes/admin/genres'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminVideosIndexRouteImport } from './routes/admin/videos.index'
import { Route as AdminVideosSeriesIdRouteImport } from './routes/admin/videos.$seriesId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGenresRoute = AdminGenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVideosIndexRoute = AdminVideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVideosSeriesIdRoute = AdminVideosSeriesIdRouteImport.update({
  id: '/videos/$seriesId',
  path: '/videos/$seriesId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/form': typeof FormRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/genres': typeof AdminGenresRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/videos/$seriesId': typeof AdminVideosSeriesIdRoute
  '/admin/videos/': typeof AdminVideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/form': typeof FormRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/genres': typeof AdminGenresRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin': typeof AdminIndexRoute
  '/admin/videos/$seriesId': typeof AdminVideosSeriesIdRoute
  '/admin/videos': typeof AdminVideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/form': typeof FormRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/genres': typeof AdminGenresRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/videos/$seriesId': typeof AdminVideosSeriesIdRoute
  '/admin/videos/': typeof AdminVideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/form'
    | '/login'
    | '/register'
    | '/admin/genres'
    | '/admin/profile'
    | '/admin/'
    | '/admin/videos/$seriesId'
    | '/admin/videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/form'
    | '/login'
    | '/register'
    | '/admin/genres'
    | '/admin/profile'
    | '/admin'
    | '/admin/videos/$seriesId'
    | '/admin/videos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/form'
    | '/login'
    | '/register'
    | '/admin/genres'
    | '/admin/profile'
    | '/admin/'
    | '/admin/videos/$seriesId'
    | '/admin/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FormRoute: typeof FormRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/genres': {
      id: '/admin/genres'
      path: '/genres'
      fullPath: '/admin/genres'
      preLoaderRoute: typeof AdminGenresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/videos/': {
      id: '/admin/videos/'
      path: '/videos'
      fullPath: '/admin/videos/'
      preLoaderRoute: typeof AdminVideosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/videos/$seriesId': {
      id: '/admin/videos/$seriesId'
      path: '/videos/$seriesId'
      fullPath: '/admin/videos/$seriesId'
      preLoaderRoute: typeof AdminVideosSeriesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminGenresRoute: typeof AdminGenresRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminVideosSeriesIdRoute: typeof AdminVideosSeriesIdRoute
  AdminVideosIndexRoute: typeof AdminVideosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGenresRoute: AdminGenresRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminVideosSeriesIdRoute: AdminVideosSeriesIdRoute,
  AdminVideosIndexRoute: AdminVideosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FormRoute: FormRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
