export * from "@repo/media-service";
export * from "./scheduler";
export {
  RELAY_CDN_HOST_FRAGMENTS,
  RELAY_CDN_REFERER,
  RELAY_EMBED_REFERER,
  EMBED_UPSTREAM_ORIGIN,
  EMBED_USER_AGENT,
  MOBILE_VIDEO_SHIM,
  AD_SUPPRESSION_SHIM,
  VIDHIDE_ANTI_CLICKJACK_CSS,
  KNOWN_AD_SCRIPT_PATTERNS,
  BLOCKED_APP_SCHEMES,
  EMBED_SW_CLEANUP_SHIM,
  DEBUG_LOGGER_SHIM,
  WEBCRYPTO_INSECURE_POLYFILL_SHIM,
  resolveRelayReferer,
  buildProxyBaseHref,
  isBlockedAdAsset,
  isBlockedAppSchemeUrl,
  stripKnownAdScripts,
  sanitizeHtmlContent,
  buildRelayInterceptorShim,
  buildServerRenderedEmbedDocument,
  buildEmbedErrorDocument,
  enforceMobileVideoAttributes,
} from "./internal/proxy-helpers";
